### ISSUE TITLE
ng add, Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by semla** [daniel-sc/ng-extract-i18n-merge#114]
```
$ ng add ng-extract-i18n-merge --verbose
✔ Determining Package Manager
  › Using package manager: npm
✔ Searching for compatible package version
  › Found compatible package version: ng-extract-i18n-merge@2.12.0.
✔ Loading package information from registry
✖ Class extends value undefined is not a constructor or null

Locating potential npmrc files:
An unhandled exception occurred: Class extends value undefined is not a constructor or null
See "/tmp/ng-v9OfIP/angular-errors.log" for further details.

```

```
$ cat /tmp/ng-v9OfIP/angular-errors.log
[error] TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/user/project/node_modules/@listr2/prompt-adapter-inquirer/dist/index.cjs:30:62)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/user/project/node_modules/@angular/cli/src/commands/add/cli.js:251:108
    at async Task.task [as taskFn] (/home/user/project/node_modules/@angular/cli/src/commands/add/cli.js:251:60)
    at async Task.run (/home/user/project/node_modules/@angular/cli/node_modules/listr2/dist/index.cjs:2143:11)
```

**Comment by daniel-sc** [comment]
@semla thanks for this report - could you add which versions of node/os/angular you are using? if it is possible to provide a reproduction that would be even greater :)

**Comment by semla** [comment]
@daniel-sc thanks for the quick reply and this package.

Debian 12, angular 18.2.3, node v20.16.0, typescript 5.4.5.
It's a project that has been around since probably angular2.
No idea if it is related but there is an oddity in the libraries, where the localize function is imported like this:
import { ɵ$localize } from '@angular/localize';

**Comment by semla** [comment]
I cleaned up the project and the problem went away, closing
